Unify utilities into a single service for containerization (#372)
liquality/atomicagent pull request #376
Opened 2021-08-26 14:44 UTC by manicprone

This PR contains the follow-up effort for containerizing the atomic agent (as a full service).

It now supports dockerized versions of:

* The "service" (migrate, api, worker in a single container)
* The "full system" (atomic agent service + all services per the docker test config)

The README has been updated to describe these options (and I cleaned the doc up a bit): https://github.com/liquality/atomicagent/blob/unified/README.md

@harshjv - I added back the "force" logic and the KEEP_ALIVE env var for the migrate service, to support the current codebase setup. It is understood we are eventually moving to a UI-based initialization process (where the user determines which markets to seed into the database). But for now, this solution allows us to support: (1) containerization (2) automated testing

I also added "paths" to the test.yml action, to try and trigger the automated tests only on relevant code changes.

2021-09-06 14:39 UTC, harshjv requested changes

2021-09-06 14:39 UTC, harshjv commented on .github/workflows/test.yml
> +    paths:
can we use `paths-ignore` instead? like;
```
- '**.md'
- '**.Dockerfile'
```

2021-09-06 14:39 UTC, harshjv commented on env/personal/config.personal.toml
>  authdbname = "admin"
you have removed these variables in this commit. can you remove them from here too?

2021-09-06 14:39 UTC, harshjv commented on package.json
> +    "api-service": "KEEP_ALIVE=true node src/index.js",
it seems `api-service` will also trigger `worker`. can we rework on script name?

2021-09-06 14:39 UTC, harshjv commented on src/index.js
> +  await require('./migrate').run(migrateOpts)
we discussed to keep `migrate` out of normal booting process.

2021-09-07 12:48 UTC, manicprone commented on src/index.js
> +  await require('./migrate').run(migrateOpts)
But, we need it for now, to make the service work. It is just until we have the new solution. Otherwise, we need to create an entirely separate infrastructure setup, just to deploy the migrate logic and init the database.

2021-09-22 17:53 UTC, closed without merging