feat: Update near packages to 1.11.0
liquality/atomicagent pull request #397
Opened 2021-12-03 11:56 UTC by AndonMitev

Update near packages to 1.11.0

2021-12-03 13:10 UTC, harshjv requested changes

2021-12-03 13:10 UTC, harshjv commented on package.json
> +    "@liquality/near-js-wallet-provider": "^1.11.0",
can we use exact version here?

2021-12-03 15:53 UTC, beemi approved these changes

2021-12-06 09:25 UTC, harshjv approved these changes

2021-12-06 10:03 UTC, merged