feat: Update packages for CAL to 1.12.0
liquality/atomicagent pull request #411
Opened 2022-01-17 15:12 UTC by AndonMitev

2022-01-17 15:13 UTC, harshjv requested changes

2022-01-18 06:56 UTC, AndonMitev commented on package.json
> +  "version": "0.4.101",
What should be right one, sorry not sure what the put there. Is it `0.4.10-next.12` ok?

2022-01-18 06:57 UTC, AndonMitev commented on package.json
> +  "version": "0.4.101",
I've updated to `0.4.10-next.12`

2022-01-18 11:00 UTC, beemi approved these changes

2022-01-18 11:00 UTC, merged