feat: replace CAL with Chainify
liquality/atomicagent pull request #441
Opened 2022-05-17 09:31 UTC by kraikov

2022-05-20 14:25 UTC, bradleySuira approved these changes
LGTM

2022-05-24 10:39 UTC, harshjv requested changes
Overall, PR is looking good. Once tests are green, we should be able to merge this.

2022-05-24 10:39 UTC, harshjv commented on package.json
> +    "@chainify/bitcoin": "portal:/Users/kraykov/Documents/workspaces/liquality/chainabstractionlayer-2/packages/bitcoin",
is it normal to commit local dev paths to package.json?

2022-05-24 10:39 UTC, harshjv commented on src/utils/chainify.js
> +  if (new BN(allowance.toString()).gte(amount.toString())) {
is `.toString()` necessary here?

2022-05-24 10:39 UTC, harshjv commented on src/utils/chainify.js
> +  const allowanceCallData = `0xdd62ed3e000000000000000000000000${remove0x(user)}000000000000000000000000${HTLC_ADDRESS}`
can you use `array.join('')` here & below for better readability?

2022-05-24 12:28 UTC, kraikov commented on package.json
> +    "@chainify/bitcoin": "portal:/Users/kraykov/Documents/workspaces/liquality/chainabstractionlayer-2/packages/bitcoin",
no :)

2022-05-24 20:43 UTC, kraikov commented
> Overall, PR is looking good. Once tests are green, we should be able to merge this.

I'm not sure how to make tests green as I'm not even able to run the tests from the dev branch locally.

2022-05-26 06:03 UTC, harshjv approved these changes
LGTM

2022-05-26 07:16 UTC, merged